"""Initial migration with chat models

Revision ID: 407fee368daa
Revises: 
Create Date: 2025-07-16 06:47:02.188330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '407fee368daa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('chat_thread_id', sa.Integer(), nullable=False),
    sa.Column('agent_search_full_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_queries', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_results', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['chat_thread_id'], ['chat_thread.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('chat_message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_result')
    op.drop_table('chat_message')
    op.drop_table('chat_thread')
    # ### end Alembic commands ###
