"""Add title field to chat_thread table

Revision ID: 6078c0a2b97b
Revises: 407fee368daa
Create Date: 2025-07-16 14:23:19.418035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6078c0a2b97b'
down_revision: Union[str, None] = '407fee368daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_thread', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_thread', 'title')
    # ### end Alembic commands ###
