"""Add user_id fields to chat_thread and chat_message tables

Revision ID: f8a9b2c3d4e5
Revises: 6078c0a2b97b
Create Date: 2025-01-16 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f8a9b2c3d4e5'
down_revision: Union[str, None] = '6078c0a2b97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add user_id column to chat_thread table (UUID type for Supabase Auth)
    op.add_column('chat_thread', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Add user_id column to chat_message table (UUID type for Supabase Auth)
    op.add_column('chat_message', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Create indexes for better query performance
    op.create_index('ix_chat_thread_user_id', 'chat_thread', ['user_id'])
    op.create_index('ix_chat_message_user_id', 'chat_message', ['user_id'])
    
    # NOTE: For production, you would need to populate existing records with user_id values
    # For now, existing records will have NULL user_id and new records will have proper user_id
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes first
    op.drop_index('ix_chat_message_user_id', 'chat_message')
    op.drop_index('ix_chat_thread_user_id', 'chat_thread')
    
    # Drop columns
    op.drop_column('chat_message', 'user_id')
    op.drop_column('chat_thread', 'user_id')
    
    # ### end Alembic commands ### 